services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kayo
      POSTGRES_PASSWORD: kayo
      POSTGRES_DB: kayo
    ports:
      - "5432:5432"
    volumes:
      - kayo_pg:/var/lib/postgresql/data

volumes:
  kayo_pg:
