export const seedCities = [
  {
    id: "tokyo",
    slug: "tokyo",
    region: "kanto",
    nameEn: "Tokyo",
    nameJa: "東京",
    nameZh: "东京",
    prefectureEn: "Tokyo Metropolis",
    prefectureJa: "東京都",
    prefectureZh: "东京都",
  },
  {
    id: "kyoto",
    slug: "kyoto",
    region: "kinki",
    nameEn: "Kyoto",
    nameJa: "京都",
    nameZh: "京都",
    prefectureEn: "Kyoto Prefecture",
    prefectureJa: "京都府",
    prefectureZh: "京都府",
  },
  {
    id: "osaka",
    slug: "osaka",
    region: "kinki",
    nameEn: "Osaka",
    nameJa: "大阪",
    nameZh: "大阪",
    prefectureEn: "Osaka Prefecture",
    prefectureJa: "大阪府",
    prefectureZh: "大阪府",
  },
  {
    id: "hakone",
    slug: "hakone",
    region: "kanto",
    nameEn: "Hakone",
    nameJa: "箱根",
    nameZh: "箱根",
    prefectureEn: "Kanagawa Prefecture",
    prefectureJa: "神奈川県",
    prefectureZh: "神奈川县",
  },
  {
    id: "sapporo",
    slug: "sapporo",
    region: "hokkaido",
    nameEn: "Sapporo",
    nameJa: "札幌",
    nameZh: "札幌",
    prefectureEn: "Hokkaido",
    prefectureJa: "北海道",
    prefectureZh: "北海道",
  },
  {
    id: "naha",
    slug: "naha",
    region: "okinawa",
    nameEn: "Naha",
    nameJa: "那覇",
    nameZh: "那霸",
    prefectureEn: "Okinawa Prefecture",
    prefectureJa: "沖縄県",
    prefectureZh: "冲绳县",
  },
  {
    id: "kanazawa",
    slug: "kanazawa",
    region: "chubu",
    nameEn: "Kanazawa",
    nameJa: "金沢",
    nameZh: "金泽",
    prefectureEn: "Ishikawa Prefecture",
    prefectureJa: "石川県",
    prefectureZh: "石川县",
  },
  {
    id: "hiroshima",
    slug: "hiroshima",
    region: "chugoku",
    nameEn: "Hiroshima",
    nameJa: "広島",
    nameZh: "广岛",
    prefectureEn: "Hiroshima Prefecture",
    prefectureJa: "広島県",
    prefectureZh: "广岛县",
  },
] as const;

export const seedHotels = [
  {
    id: "h-asakusa-andon",
    slug: "asakusa-andon",
    cityId: "tokyo",
    kind: "ryokan",
    nameEn: "Andon House Asakusa",
    nameJa: "行燈の宿 浅草",
    nameZh: "浅草行灯宿",
    summaryEn:
      "Nine rooms above a timber shop-street. The night watch still walks the lane at ten.",
    summaryJa:
      "木造の店先が続く通りの上、九室。夜十時に今も提灯の見回りが通る。",
    summaryZh:
      "木造店铺街上的九间客房。夜里十点，提灯巡夜的人仍会走过巷子。",
    bodyEn:
      "The house sits eight minutes on foot from Asakusa Station, on a street that still sells brushes and incense before noon. Rooms are six-tatami, with a shared cedar bath on the second floor that holds two people if you sit still. Breakfast is grilled fish and rice, served until 8:40 because the cook then opens the ground-floor shop. Check-in is from 16:00; luggage can be left from 11:00. English is spoken at the desk until 21:00, after which a night note in three languages hangs on the door.",
    bodyJa:
      "浅草駅から徒歩八分。午前中は筆と線香を売る店が並ぶ通りに面しています。部屋は六畳。二階の杉風呂は、静かに座れば二人まで。朝食は焼き魚とご飯で、料理人は八時四十分で店を開けるため、それまでです。チェックインは十六時から。荷物は十一時から預けられます。窓口の英語対応は二十一時まで。以降は三言語の夜間メモが扉に掛かります。",
    bodyZh:
      "距浅草站步行八分钟，门前的街上午时还在卖毛笔和线香。客房为六叠，二楼的杉木浴池安静坐下可容两人。早餐是烤鱼配米饭，做到八点四十，因为厨子接着要开一楼的铺子。入住从十六点开始，行李十一点起可寄存。柜台英语服务到二十一点，之后门上挂着三语夜间留言。",
    addressEn: "2-11-8 Asakusa, Taito-ku, Tokyo",
    addressJa: "東京都台東区浅草2-11-8",
    addressZh: "东京都台东区浅草2-11-8",
    stationEn: "Asakusa Station (Ginza / Asakusa / Tobu lines)",
    stationJa: "浅草駅（銀座線・浅草線・東武線）",
    stationZh: "浅草站（银座线、浅草线、东武线）",
    walkMinutes: 8,
    priceFromYen: 18400,
    rating: 4.6,
    reviewCount: 128,
    rooms: 9,
    checkIn: "16:00",
    checkOut: "10:00",
    image: "/images/hotels/hotel-tokyo-ryokan.png",
    amenities: "tatami,breakfast,english_desk,luggage,yukata,shared_bath",
  },
  {
    id: "h-higashiyama-ishi",
    slug: "higashiyama-ishi",
    cityId: "kyoto",
    kind: "machiya",
    nameEn: "Ishi-an, Higashiyama",
    nameJa: "石庵 東山",
    nameZh: "东山石庵",
    summaryEn:
      "A restored machiya on a stone lane. Two rooms share a well in the courtyard.",
    summaryJa:
      "石畳の路地に面した改装町家。二室で中庭の井戸を分け合う。",
    summaryZh: "石板巷里改建的町屋。两间客房共用庭院里的一口井。",
    bodyEn:
      "Gion-Shijō is six minutes on foot; the last bus up the hill leaves at 23:12. The house keeps the lattice and the earthen walls. There is no television. Breakfast is ochazuke with pickled greens from Ohara, not a hotel buffet. The well water is for rinsing hands, not drinking — the kettle uses filtered city water, written on a card in the kitchen. Private bath attached to each room. The owner lives two doors down and comes at 15:30 to open the gate.",
    bodyJa:
      "祇園四条から徒歩六分。坂を上がる最終バスは二十三時十二分です。格子と土壁はそのまま。テレビはありません。朝はホテルのビュッフェではなく、大原の漬物でお茶漬け。井戸水は手を清める用で、飲むのはやかんの水道水です。その旨を台所の札に書いてあります。風呂は各室付き。持ち主は二軒先に住み、十五時半に門を開けに来ます。",
    bodyZh:
      "距祇园四条步行六分钟，上坡末班公交二十三点十二分开。格子窗和土墙都留着，没有电视。早餐不是酒店自助，而是大原的咸菜配茶泡饭。井水只洗手，饮用是壶里的自来水，厨房有纸条写明。每间有独立浴室。屋主住在隔两户，十五点半来开门。",
    addressEn: "349-2 Kōdaiji-minami-monzen-chō, Higashiyama-ku, Kyoto",
    addressJa: "京都市東山区高台寺南門前町349-2",
    addressZh: "京都市东山区高台寺南门前町349-2",
    stationEn: "Gion-Shijō Station (Keihan)",
    stationJa: "祇園四条駅（京阪）",
    stationZh: "祇园四条站（京阪）",
    walkMinutes: 6,
    priceFromYen: 27800,
    rating: 4.8,
    reviewCount: 74,
    rooms: 2,
    checkIn: "15:30",
    checkOut: "11:00",
    image: "/images/hotels/hotel-kyoto-machiya.png",
    amenities: "tatami,breakfast,private_bath,luggage,yukata",
  },
  {
    id: "h-nakanoshima-yodo",
    slug: "nakanoshima-yodo",
    cityId: "osaka",
    kind: "business",
    nameEn: "Yodo Window Hotel",
    nameJa: "淀の窓ホテル",
    nameZh: "淀窗饭店",
    summaryEn:
      "A compact room over the Nakanoshima canal. The desk faces the water, not the television.",
    summaryJa:
      "中之島の川に面した小さな部屋。机はテレビではなく水面に向いている。",
    summaryZh: "中之岛运河边的小房间。书桌对着水面，而不是电视。",
    bodyEn:
      "Four minutes from Yodoyabashi Station, useful if you arrive on the Keihan line from Kyoto and leave the next morning for Shin-Osaka. Rooms are 16 m². The canal window is single-glazed; ask for a courtyard room if you sleep lightly. Breakfast is a tray in the lobby from 6:30 — onigiri, miso, a boiled egg — because most guests catch the 7:24 Hikari. Coin laundry on the third floor runs until 23:00. The desk can charge an ICOCA card.",
    bodyJa:
      "淀屋橋駅から徒歩四分。京都から京阪で着いて翌朝に新大阪へ出る人向きです。部屋は十六平方メートル。川側は一枚ガラスなので、眠りが浅い方は中庭側を頼んでください。朝食は六時半からロビーの膳——おにぎり、味噌汁、ゆで卵。多くの客が七時二十四分のひかりに乗るためです。三階のコインランドリーは二十三時まで。窓口でICOCAにチャージできます。",
    bodyZh:
      "距淀屋桥站步行四分钟，适合从京都坐京阪抵达、次日一早去新大阪的人。房间十六平方米。临河是单层玻璃，浅眠者请要院内侧。早餐六点半在大堂以托盘供应——饭团、味噌汤、水煮蛋——因为多数客人赶七点二十四分的光号。三楼投币洗衣到二十三点。柜台可为ICOCA充值。",
    addressEn: "1-3-4 Nakanoshima, Kita-ku, Osaka",
    addressJa: "大阪市北区中之島1-3-4",
    addressZh: "大阪市北区中之岛1-3-4",
    stationEn: "Yodoyabashi Station (Midosuji / Keihan)",
    stationJa: "淀屋橋駅（御堂筋線・京阪）",
    stationZh: "淀屋桥站（御堂筋线、京阪）",
    walkMinutes: 4,
    priceFromYen: 14200,
    rating: 4.3,
    reviewCount: 211,
    rooms: 86,
    checkIn: "15:00",
    checkOut: "10:00",
    image: "/images/hotels/hotel-osaka-nakanoshima.png",
    amenities: "breakfast,english_desk,luggage,late_checkin,ic_card_charge,laundry",
  },
  {
    id: "h-hakone-sugi",
    slug: "hakone-sugi-yu",
    cityId: "hakone",
    kind: "onsen",
    nameEn: "Sugi-yu, Hakone-Yumoto",
    nameJa: "杉湯 箱根湯本",
    nameZh: "箱根汤本杉汤",
    summaryEn:
      "Twelve minutes uphill from Hakone-Yumoto. The outdoor bath looks into cedar, not a car park.",
    summaryJa:
      "箱根湯本から坂を十二分。露天は駐車場ではなく杉に面している。",
    summaryZh: "从箱根汤本上坡十二分钟。露天浴对着杉林，而不是停车场。",
    bodyEn:
      "The Romancecar stops at Hakone-Yumoto; from there a hotel car runs on the hour until 19:00, or you walk the old road. The water is mildly sulphurous, 42 °C in the cedar tub, 38 °C in the stone one. Dinner is kaiseki with two fish from Odawara, served at 18:00 or 19:30. Day-trippers are not admitted to the bath. Yukata and a winter haori are in the room. If you arrive with a large suitcase, say so when you book — the last stretch is a flight of stone steps.",
    bodyJa:
      "ロマンスカーは箱根湯本止まり。そこから宿の車が十九時まで毎正時、あるいは旧道を歩きます。湯は弱い硫黄泉。杉舟が四十二度、石船が三十八度。夕食は小田原の魚二品を入れた会席で、十八時か十九時半。日帰り入浴は受けていません。部屋に浴衣と冬羽織。大荷物の方は予約時に書いてください。最後は石段です。",
    bodyZh:
      "浪漫特快到箱根汤本为止。从那里旅馆接驳车十九点前每逢整点一班，也可走旧道。泉水是淡硫磺，杉木浴槽四十二度，石槽三十八度。晚餐是会席，含小田原的两道鱼，十八点或十九点半入座。不接待日归入浴。房内有浴衣和冬羽织。若带大行李箱，预订时请写明——最后一段是石阶。",
    addressEn: "Yumoto 684, Hakone-machi, Ashigarashimo-gun, Kanagawa",
    addressJa: "神奈川県足柄下郡箱根町湯本684",
    addressZh: "神奈川县足柄下郡箱根町汤本684",
    stationEn: "Hakone-Yumoto Station (Odakyu / Hakone Tozan)",
    stationJa: "箱根湯本駅（小田急・箱根登山）",
    stationZh: "箱根汤本站（小田急、箱根登山）",
    walkMinutes: 12,
    priceFromYen: 36500,
    rating: 4.7,
    reviewCount: 96,
    rooms: 14,
    checkIn: "15:00",
    checkOut: "11:00",
    image: "/images/hotels/hotel-hakone-onsen.png",
    amenities: "onsen,tatami,breakfast,dinner,private_bath,yukata,luggage",
  },
  {
    id: "h-maruyama-birch",
    slug: "maruyama-birch",
    cityId: "sapporo",
    kind: "lodge",
    nameEn: "Birch Lodge Maruyama",
    nameJa: "白樺ロッジ 円山",
    nameZh: "圆山白桦小屋",
    summaryEn:
      "A wooden house at the foot of Maruyama. Firewood is stacked by the door; the tram stop is nine minutes.",
    summaryJa:
      "円山の麓の木の家。薪は玄関に積んである。市電の停留場まで九分。",
    summaryZh: "圆山脚下的木屋。门口码着柴火，电车停靠站九分钟。",
    bodyEn:
      "Useful if you want the zoo, the shrine, and a quiet night without staying in Susukino. Six rooms. The stove in the common room is lit from November to March; after that the heat is electric and slower. Breakfast is toast, butter from Nakashibetsu, and coffee poured until 9:00. Ski buses to Kokusai pick up at Maruyama-koen Station, not at the lodge. In February the walk from the tram can take fifteen minutes after a night of snow.",
    bodyJa:
      "動物園と神社の近くで、すすきのには泊まりたくない人向けです。六室。居間のストーブは十一月から三月。以降は電気で、温まるまで時間が要ります。朝は中標津のバターとトースト、コーヒーは九時まで。国際へのスキーバスは円山公園駅発で、ロッジ前には来ません。二月は一夜の雪のあと、市電から十五分かかることもあります。",
    bodyZh:
      "适合想去动物园和神社、又不想住在薄野的人。六间房。客厅火炉十一月到三月烧，之后改电暖，热得慢。早餐是中标津黄油配吐司，咖啡供应到九点。去国际滑雪场的巴士从圆山公园站发，不到小屋门口。二月若夜里下过雪，从电车站走可能要十五分钟。",
    addressEn: "3-7 Minami 1-jo Nishi 24-chome, Chuo-ku, Sapporo",
    addressJa: "札幌市中央区南1条西24丁目3-7",
    addressZh: "札幌市中央区南1条西24丁目3-7",
    stationEn: "Maruyama-koen Station (Tozai line) / tram Nishi-15-chome",
    stationJa: "円山公園駅（東西線）／市電 西15丁目",
    stationZh: "圆山公园站（东西线）／路面电车 西15丁目",
    walkMinutes: 9,
    priceFromYen: 16800,
    rating: 4.5,
    reviewCount: 61,
    rooms: 6,
    checkIn: "16:00",
    checkOut: "10:00",
    image: "/images/hotels/hotel-sapporo-lodge.png",
    amenities: "breakfast,luggage,laundry,english_desk",
  },
  {
    id: "h-kokusai-shisa",
    slug: "kokusai-shisa",
    cityId: "naha",
    kind: "guesthouse",
    nameEn: "Shisa Stay Kokusai-dori",
    nameJa: "シーサー宿 国際通り",
    nameZh: "国际通风狮宿",
    summaryEn:
      "A guesthouse behind Kokusai-dori. The roof still keeps a shisa; the sea is a twenty-minute bus.",
    summaryJa:
      "国際通りの裏手。屋根にシーサーが残る。海まではバス二十分。",
    summaryZh: "国际通背面的民宿。屋顶仍蹲着风狮爷。去海边要坐二十分钟公交。",
    bodyEn:
      "Makishi Station is five minutes on foot. Rooms are mixed: two Japanese-style, seven Western with bunks. The kitchen is open until 22:00; there is a rice cooker and a note asking you not to fry goya at midnight. The airport limousine stops at Kencho-mae, eight minutes’ walk. Typhoon season (August–September) can cancel ferries to the outer islands — the desk posts the port bulletin each morning. No breakfast; the market opens at 8:00 across the street.",
    bodyJa:
      "牧志駅から徒歩五分。和室二、二段ベッドの洋室七。台所は二十二時まで。炊飯器あり。夜中にゴーヤを揚げないでほしい、と札が書いてあります。空港リムジンは県庁前、徒歩八分。台風の季節（八〜九月）は離島の船が欠航します。窓口は毎朝、港の掲示を貼ります。朝食なし。向かいで市場が八時に開きます。",
    bodyZh:
      "距牧志站步行五分钟。和室两间，上铺西式七间。厨房开放到二十二点，有电饭煲，纸条请勿半夜炸苦瓜。机场巴士停县厅前，步行八分钟。台风季（八至九月）离岛船班会停，柜台每天早上张贴港口告示。不含早餐，街对面市场八点开门。",
    addressEn: "2-4-12 Makishi, Naha, Okinawa",
    addressJa: "沖縄県那覇市牧志2-4-12",
    addressZh: "冲绳县那霸市牧志2-4-12",
    stationEn: "Makishi Station (Yui Rail)",
    stationJa: "牧志駅（ゆいレール）",
    stationZh: "牧志站（单轨）",
    walkMinutes: 5,
    priceFromYen: 9600,
    rating: 4.2,
    reviewCount: 183,
    rooms: 9,
    checkIn: "16:00",
    checkOut: "10:00",
    image: "/images/hotels/hotel-naha-guesthouse.png",
    amenities: "luggage,laundry,english_desk,kitchen",
  },
  {
    id: "h-chaya-kage",
    slug: "higashi-chaya-kage",
    cityId: "kanazawa",
    kind: "ryokan",
    nameEn: "Kage, Higashi Chaya",
    nameJa: "影 東茶屋",
    nameZh: "东茶屋「影」",
    summaryEn:
      "Four rooms in a tea-house street. The garden is moss, not gravel, and closes at dusk.",
    summaryJa:
      "茶屋街の四室。庭は砂利ではなく苔で、日暮れに門を閉じる。",
    summaryZh: "茶屋街里的四间房。庭院是苔藓而非白砂，黄昏关院门。",
    bodyEn:
      "The Hokuriku Shinkansen stops at Kanazawa; from there a bus to Hashiba-cho takes twelve minutes, then a three-minute walk. Shoes off at the street door. Gold leaf is sold two shops down — the house does not sell it, and will not arrange a workshop. Dinner can be added (kaiseki, 8,800 yen) if you write two days ahead. The nearest convenience store is eight minutes; after 21:00 the lane is dark. Kenrokuen is a twenty-minute walk at opening (7:00 in summer).",
    bodyJa:
      "北陸新幹線は金沢駅。そこから橋場町行きバス十二分、徒歩三分。玄関で靴を脱ぎます。金箔は二軒先で売っています。当家では扱わず、体験も手配しません。夕食の会席（八千八百円）は二日前までに。コンビニは八分。二十一時以降、路地は暗いです。兼六園は夏の開門七時なら徒歩二十分。",
    bodyZh:
      "北陆新干线到金泽站，再坐十二分钟公交到桥场町，步行三分钟。进门脱鞋。金箔在隔两家有卖，本店不售，也不代订体验。晚餐会席（八千八百日元）须提前两天。便利店八分钟，二十一点后巷子很暗。兼六园若赶夏季七点开门，步行二十分钟。",
    addressEn: "1-13-2 Higashiyama, Kanazawa, Ishikawa",
    addressJa: "石川県金沢市東山1-13-2",
    addressZh: "石川县金泽市东山1-13-2",
    stationEn: "Kanazawa Station (Hokuriku Shinkansen), then bus to Hashiba-cho",
    stationJa: "金沢駅（北陸新幹線）から橋場町バス",
    stationZh: "金泽站（北陆新干线）转桥场町公交",
    walkMinutes: 15,
    priceFromYen: 31200,
    rating: 4.9,
    reviewCount: 42,
    rooms: 4,
    checkIn: "16:00",
    checkOut: "11:00",
    image: "/images/hotels/hotel-kanazawa.png",
    amenities: "tatami,breakfast,dinner,private_bath,yukata,english_desk",
  },
] as const;

export const seedTickets = [
  {
    id: "t-nozomi-tyo-kyo",
    slug: "nozomi-tokyo-kyoto",
    kind: "shinkansen",
    fromCityId: "tokyo",
    toCityId: "kyoto",
    operatorEn: "JR Central / JR West",
    operatorJa: "JR東海・JR西日本",
    operatorZh: "JR东海、JR西日本",
    nameEn: "Nozomi, Tokyo → Kyoto",
    nameJa: "のぞみ 東京→京都",
    nameZh: "希望号 东京→京都",
    summaryEn:
      "The fastest Hikari-class is Nozomi. Tokyo to Kyoto in 2 h 12 m on a good path. The JR Pass does not cover Nozomi; Hikari is 2 h 40 m.",
    summaryJa:
      "最速はのぞみ。順調なら東京—京都二時間十二分。JRパスはのぞみ不可。ひかりは約二時間四十分。",
    summaryZh:
      "最快是希望号。顺畅时东京到京都二小时十二分。JR Pass不能坐希望号；光号约二小时四十分。",
    durationMin: 132,
    priceUnreservedYen: 13850,
    priceReservedYen: 14420,
    priceGreenYen: 19390,
    dailyDepartures: 32,
    firstDeparture: "06:00",
    lastDeparture: "21:24",
    image: "/images/tickets/ticket-shinkansen.png",
  },
  {
    id: "t-hikari-tyo-osa",
    slug: "hikari-tokyo-osaka",
    kind: "shinkansen",
    fromCityId: "tokyo",
    toCityId: "osaka",
    operatorEn: "JR Central / JR West",
    operatorJa: "JR東海・JR西日本",
    operatorZh: "JR东海、JR西日本",
    nameEn: "Hikari, Tokyo → Shin-Osaka",
    nameJa: "ひかり 東京→新大阪",
    nameZh: "光号 东京→新大阪",
    summaryEn:
      "Covered by the national JR Pass. Two or three extra stops versus Nozomi. Shin-Osaka, not Osaka Station.",
    summaryJa:
      "全国JRパスで乗れます。のぞみより二、三駅多い。着くのは新大阪で、大阪駅ではありません。",
    summaryZh:
      "全国JR Pass可用。比希望号多停两三站。到达的是新大阪，不是大阪站。",
    durationMin: 170,
    priceUnreservedYen: 14240,
    priceReservedYen: 14810,
    priceGreenYen: 19880,
    dailyDepartures: 16,
    firstDeparture: "06:33",
    lastDeparture: "20:33",
    image: "/images/tickets/ticket-shinkansen.png",
  },
  {
    id: "t-romance-tyo-hak",
    slug: "romancecar-shinjuku-hakone",
    kind: "limited_express",
    fromCityId: "tokyo",
    toCityId: "hakone",
    operatorEn: "Odakyu Electric Railway",
    operatorJa: "小田急電鉄",
    operatorZh: "小田急电铁",
    nameEn: "Romancecar, Shinjuku → Hakone-Yumoto",
    nameJa: "ロマンスカー 新宿→箱根湯本",
    nameZh: "浪漫特快 新宿→箱根汤本",
    summaryEn:
      "All seats reserved. The front observation car is sold separately. 85 minutes when it runs as a limited express.",
    summaryJa:
      "全車指定席。先頭の展望席は別料金。特急運転なら八十五分。",
    summaryZh: "全部指定席。车头展望座另售。特急运行时八十五分钟。",
    durationMin: 85,
    priceUnreservedYen: null,
    priceReservedYen: 2470,
    priceGreenYen: null,
    dailyDepartures: 18,
    firstDeparture: "07:05",
    lastDeparture: "19:45",
    image: "/images/tickets/ticket-shinkansen.png",
  },
  {
    id: "t-hokuriku-tyo-knz",
    slug: "kagayaki-tokyo-kanazawa",
    kind: "shinkansen",
    fromCityId: "tokyo",
    toCityId: "kanazawa",
    operatorEn: "JR East / JR West",
    operatorJa: "JR東日本・JR西日本",
    operatorZh: "JR东日本、JR西日本",
    nameEn: "Kagayaki, Tokyo → Kanazawa",
    nameJa: "かがやき 東京→金沢",
    nameZh: "光辉号 东京→金泽",
    summaryEn:
      "The limited-stop Hokuriku train. All reserved. 2 h 28 m. Hakutaka is slower and cheaper by a few hundred yen.",
    summaryJa:
      "北陸の最速、全車指定。二時間二十八分。はくたかは遅く、数百円安い。",
    summaryZh: "北陆最快班次，全部指定席。二小时二十八分。白鹰号较慢，便宜数百日元。",
    durationMin: 148,
    priceUnreservedYen: null,
    priceReservedYen: 14760,
    priceGreenYen: 20440,
    dailyDepartures: 10,
    firstDeparture: "06:16",
    lastDeparture: "20:20",
    image: "/images/tickets/ticket-shinkansen.png",
  },
  {
    id: "t-jal-hnd-cts",
    slug: "jal-haneda-chitose",
    kind: "domestic_flight",
    fromCityId: "tokyo",
    toCityId: "sapporo",
    operatorEn: "Japan Airlines",
    operatorJa: "日本航空",
    operatorZh: "日本航空",
    nameEn: "JAL, Haneda → New Chitose",
    nameJa: "JAL 羽田→新千歳",
    nameZh: "日航 羽田→新千岁",
    summaryEn:
      "1 h 35 m in the air. Haneda domestic is the old building; allow 45 minutes from Monorail arrival to gate on a weekday morning.",
    summaryJa:
      "空中一時間三十五分。羽田国内線は旧ターミナル側。平日朝、モノレール到着からゲートまで四十五分見てください。",
    summaryZh:
      "空中一小时三十五分。羽田国内线在旧航站一侧。工作日早晨，从单轨抵达算到登机口请留四十五分钟。",
    durationMin: 95,
    priceUnreservedYen: null,
    priceReservedYen: 28400,
    priceGreenYen: 41200,
    dailyDepartures: 22,
    firstDeparture: "06:25",
    lastDeparture: "21:00",
    image: "/images/tickets/ticket-haneda.png",
  },
  {
    id: "t-sakura-osa-hiro",
    slug: "sakura-osaka-hiroshima",
    kind: "shinkansen",
    fromCityId: "osaka",
    toCityId: "hiroshima",
    operatorEn: "JR West",
    operatorJa: "JR西日本",
    operatorZh: "JR西日本",
    nameEn: "Sakura, Shin-Osaka → Hiroshima",
    nameJa: "さくら 新大阪→広島",
    nameZh: "樱号 新大阪→广岛",
    summaryEn:
      "Sanyo Shinkansen. About 1 h 30 m. Mizuho is a few minutes faster and not on the JR Pass.",
    summaryJa:
      "山陽新幹線。およそ一時間三十分。みずほは数分早く、JRパス対象外。",
    summaryZh: "山阳新干线。约一小时三十分。瑞穗号快几分钟，不在JR Pass范围内。",
    durationMin: 90,
    priceUnreservedYen: 10450,
    priceReservedYen: 11020,
    priceGreenYen: 15240,
    dailyDepartures: 20,
    firstDeparture: "06:04",
    lastDeparture: "21:19",
    image: "/images/tickets/ticket-shinkansen.png",
  },
  {
    id: "t-ferry-hiro-miya",
    slug: "jr-ferry-miyajima",
    kind: "ferry",
    fromCityId: "hiroshima",
    toCityId: "hiroshima",
    operatorEn: "JR West Miyajima Ferry",
    operatorJa: "JR西日本宮島フェリー",
    operatorZh: "JR西日本宫岛渡轮",
    nameEn: "JR ferry, Miyajimaguchi → Miyajima",
    nameJa: "JR船 宮島口→宮島",
    nameZh: "JR渡轮 宫岛口→宫岛",
    summaryEn:
      "Ten minutes. The JR Pass covers this boat. The torii stands in the water only near high tide — check the tide table, not the postcard.",
    summaryJa:
      "十分。JRパスで乗れます。大鳥居が海に立つのは満潮の前後だけです。絵葉書ではなく潮汐表を見てください。",
    summaryZh:
      "十分钟。JR Pass可用。大鸟居浸在海里只在满潮前后，请看潮汐表，不要看明信片。",
    durationMin: 10,
    priceUnreservedYen: 200,
    priceReservedYen: 200,
    priceGreenYen: null,
    dailyDepartures: 48,
    firstDeparture: "06:25",
    lastDeparture: "22:42",
    image: "/images/tickets/ticket-seto-ferry.png",
  },
  {
    id: "t-ana-kix-oka",
    slug: "ana-kix-naha",
    kind: "domestic_flight",
    fromCityId: "osaka",
    toCityId: "naha",
    operatorEn: "All Nippon Airways",
    operatorJa: "全日空",
    operatorZh: "全日空",
    nameEn: "ANA, Kansai → Naha",
    nameJa: "ANA 関西→那覇",
    nameZh: "全日空 关西→那霸",
    summaryEn:
      "About 2 h 10 m. Evening flights fill on Fridays. The Naha monorail starts in the terminal; buy a ticket before the queue for tourist IC.",
    summaryJa:
      "およそ二時間十分。金曜の夜便は埋まります。ゆいレールはターミナル内。観光用ICの列の前に切符を買ってください。",
    summaryZh:
      "约二小时十分。周五晚班容易满。单轨在航站楼内，请在观光IC排队之前先买车票。",
    durationMin: 130,
    priceUnreservedYen: null,
    priceReservedYen: 26800,
    priceGreenYen: 38900,
    dailyDepartures: 9,
    firstDeparture: "07:40",
    lastDeparture: "19:55",
    image: "/images/tickets/ticket-haneda.png",
  },
] as const;

export const seedRoutes = [
  {
    id: "r-golden",
    slug: "golden-route-seven",
    nights: 7,
    priceFromYen: 148000,
    region: "kanto-kinki",
    nameEn: "Seven nights on the Golden Route",
    nameJa: "黄金ルート 七泊",
    nameZh: "黄金路线 七晚",
    summaryEn:
      "Tokyo 3 · Hakone 1 · Kyoto 2 · Osaka 1. The old trunk that still matches how most first visits actually move.",
    summaryJa:
      "東京三・箱根一・京都二・大阪一。初めての日本が今もこの順で動く、古い幹線です。",
    summaryZh:
      "东京三晚、箱根一晚、京都两晚、大阪一晚。多数初次到访仍按这条旧干线走。",
    bodyEn:
      "Day 1–3 in Asakusa or nearby, so the Skytree and the river are a walk, not a subway hour. Day 4 is the Romancecar to Hakone-Yumoto and one night at an onsen — if you skip Hakone you arrive in Kyoto tired from a single long rail day. Day 5–6 in Higashiyama, walking, not a bus tour. Day 7 is the 35-minute Shinkansen to Shin-Osaka, useful if you fly out of Itami or Kansai the next morning. The price quoted is lodgings plus reserved ordinary seats, two adults, not Green Car, not meals except the Hakone dinner.",
    bodyJa:
      "一日目から三日目は浅草周辺。スカイツリーと川が徒歩圏で、地下鉄一時間にはしません。四日目はロマンスカーで箱根湯本、温泉一泊。箱根を省くと、京都着が一日の長距離の疲れになります。五・六日目は東山を歩く。バスツアーにはしません。七日目は新幹線三十五分で新大阪。翌朝伊丹か関空なら都合がよいです。表示の金額は宿と普通車指定席、大人二人。グリーン車なし。食事は箱根の夕食以外含みません。",
    bodyZh:
      "第一至三晚住浅草一带，晴空塔和河边走得到，不把地铁坐成一小时。第四天浪漫特快到箱根汤本，温泉一晚——若省箱根，到京都会是一整天火车的疲倦。第五、六天在东山走路，不坐观光巴士。第七天新干线三十五分钟到新大阪，次日从伊丹或关西出港方便。标价含住宿和普通车指定席、两位成人，不含绿色车厢；餐食除箱根晚餐外自理。",
    stops: "tokyo,hakone,kyoto,osaka",
    image: "/images/routes/route-golden.png",
  },
  {
    id: "r-hokkaido",
    slug: "hokkaido-birch-loop",
    nights: 6,
    priceFromYen: 132000,
    region: "hokkaido",
    nameEn: "Six nights, Sapporo and the birch line",
    nameJa: "札幌と白樺 六泊",
    nameZh: "札幌与白桦 六晚",
    summaryEn:
      "Fly into New Chitose, sleep in Maruyama, take one local diesel day toward the coast. Winter and October are different trips.",
    summaryJa:
      "新千歳に降り、円山に泊まり、一日は海岸へ気動車。冬と十月では別の旅です。",
    summaryZh:
      "降落新千岁，住圆山，留一天坐柴油车去海岸。冬天和十月是两种走法。",
    bodyEn:
      "Nights 1–4 in Sapporo (Maruyama if you want quiet, Susukino if you want late food). Night 5 is a local train to a coastal inn — in October the fields are cut and the KiHa cars run on time; in February you budget an extra hour for snow. Night 6 back in Sapporo for the morning flight. This route does not include Furano in winter unless you add a bus day; the lavender photographs are July. The quoted price is one domestic return-ish flight from Haneda, lodge nights, and ordinary reserved seats on the limited express where it exists.",
    bodyJa:
      "一〜四泊目は札幌（静かに円山、夜食ならすすきの）。五泊目は海岸の宿へ普通列車。十月は刈田で気動車は定時、二月は雪で一時間見てください。六泊目は朝便のため札幌に戻ります。冬の富良野はこの行程に入れていません。バスの一日を足してください。ラベンダーの写真は七月です。表示は羽田からの国内線、ロッジ、特急の普通指定がある区間です。",
    bodyZh:
      "第一至四晚札幌（求静住圆山，求夜宵住薄野）。第五晚坐普快去海岸旅馆。十月田已收割，柴油车准点；二月请为雪多留一小时。第六晚回札幌赶早班飞机。冬天的富良野不在此行程里，需另加一天巴士。薰衣草照片是七月。标价含羽田国内线、小屋住宿，以及有特急指定席的路段。",
    stops: "sapporo",
    image: "/images/routes/route-hokkaido.png",
  },
  {
    id: "r-hokuriku",
    slug: "hokuriku-tea-house",
    nights: 5,
    priceFromYen: 118000,
    region: "chubu",
    nameEn: "Five nights, Kanazawa then Kyoto",
    nameJa: "金沢から京都 五泊",
    nameZh: "金泽再到京都 五晚",
    summaryEn:
      "The Hokuriku Shinkansen made this a two-seat day. Kanazawa 2, Kyoto 3. Skip the gold-leaf workshop if you only have the afternoon.",
    summaryJa:
      "北陸新幹線で、一日二席の距離になった道です。金沢二、京都三。午後しかないなら金箔体験は省く。",
    summaryZh:
      "北陆新干线把这段变成一天两个座位的距离。金泽两晚、京都三晚。若只有下午，金箔体验就省掉。",
    bodyEn:
      "Arrive Tokyo morning, Kagayaki to Kanazawa before lunch. Two nights in Higashi Chaya — Kenrokuen at opening, the garden before tour groups. Then a Thunderbird or the Shinkansen via Tsuruga to Kyoto. Three nights in Higashiyama. This is not a coastal route; if you want the Sea of Japan, add a night in Kaga Onsen and lose a night in Kyoto.",
    bodyJa:
      "朝に東京、昼前のかがやきで金沢。東茶屋に二泊。兼六園は開門すぐ、団体の前。そこからサンダーバード、または敦賀経由の新幹線で京都。東山に三泊。日本海側の行程ではありません。加賀温泉を足すなら、京都を一泊減らします。",
    bodyZh:
      "早在东京，午饭前的光辉号到金泽。东茶屋两晚。兼六园一开门就去，赶在旅行团前。再坐雷鸟或经敦贺的新干线到京都，东山三晚。这不是日本海沿岸路线；若要加贺温泉，就从京都减一晚。",
    stops: "tokyo,kanazawa,kyoto",
    image: "/images/routes/route-hokuriku.png",
  },
  {
    id: "r-setouchi",
    slug: "setouchi-tide",
    nights: 5,
    priceFromYen: 109000,
    region: "chugoku",
    nameEn: "Five nights with the Seto tide",
    nameJa: "瀬戸の潮 五泊",
    nameZh: "濑户潮汐 五晚",
    summaryEn:
      "Osaka 1, Hiroshima 2, Miyajima 1, Osaka 1. The ferry is ten minutes; the tide decides whether the gate stands in water.",
    summaryJa:
      "大阪一・広島二・宮島一・大阪一。船は十分。鳥居が海に立つかは潮が決める。",
    summaryZh:
      "大阪一晚、广岛两晚、宫岛一晚、大阪一晚。渡轮十分钟。鸟居是否浸海，由潮水决定。",
    bodyEn:
      "Sakura from Shin-Osaka to Hiroshima (about 1 h 30 m). Two nights in the city for the Peace Park in the morning, when the school groups have not yet arrived. Then the JR ferry from Miyajimaguchi — ten minutes, covered by the JR Pass. Sleep on the island if you want the gate at high tide without the last boat back. Final night in Osaka for a morning flight. Naoshima is not on this five-night frame; it needs its own ferry day from Uno.",
    bodyJa:
      "新大阪からさくらで広島、およそ一時間三十分。市内二泊は朝の平和公園、学校が来る前。宮島口からJR船十分、パス可。満潮の鳥居を最終便に急がず見るなら島に泊まる。最終夜は翌朝の便のため大阪。直島はこの五泊には入りません。宇野から船の一日が要ります。",
    bodyZh:
      "新大阪坐樱号到广岛，约一小时三十分。市内两晚，为了早晨的和平公园，赶在学校团队之前。宫岛口JR渡轮十分钟，Pass可用。若想看满潮鸟居又不赶末班船，就在岛上住。最后一晚回大阪赶早机。直岛不在这五晚里，需要从宇野另留一天坐船。",
    stops: "osaka,hiroshima",
    image: "/images/routes/route-setouchi.png",
  },
] as const;

export const seedReviews = [
  {
    id: "rv-1",
    targetKind: "hotel",
    targetId: "h-higashiyama-ishi",
    authorEn: "Helen Ward",
    authorJa: "ヘレン・ウォード",
    authorZh: "海伦·沃德",
    fromEn: "Manchester",
    fromJa: "マンチェスター",
    fromZh: "曼彻斯特",
    bodyEn:
      "The well is real. They wrote in the kitchen that the kettle is tap water. I slept without a television and did not miss it. The 23:12 bus is the last one worth catching.",
    bodyJa:
      "井戸は本物です。やかんは水道、と台所に書いてありました。テレビなしで眠り、不便ではありませんでした。バスは二十三時十二分が、降りるに値する最終です。",
    bodyZh:
      "那口井是真的。厨房写着壶里是自来水。没有电视也能睡，并不觉得缺。二十三点十二分那班车，是值得赶上的末班。",
    rating: 5,
    stayMonth: "2026-03",
    avatar: "/images/avatars/avatar-helen.png",
  },
  {
    id: "rv-2",
    targetKind: "hotel",
    targetId: "h-asakusa-andon",
    authorEn: "Chen Wei",
    authorJa: "陳偉",
    authorZh: "陈伟",
    fromEn: "Hangzhou",
    fromJa: "杭州",
    fromZh: "杭州",
    bodyEn:
      "The night watch really does pass at ten. The shared bath is small; go at 21:30 after the families. Desk English was clear until nine, then the note on the door was enough.",
    bodyJa:
      "十時の見回りは本当に来ました。共同風呂は狭い。家族が上がった二十一時半がよいです。窓口の英語は二十一時までで、あとは扉のメモで足りました。",
    bodyZh:
      "十点的巡夜真的会来。公共浴池很小，等家人用完，九点半去正好。柜台英语到九点，之后门上的留言就够了。",
    rating: 5,
    stayMonth: "2025-11",
    avatar: "/images/avatars/avatar-wei.png",
  },
  {
    id: "rv-3",
    targetKind: "route",
    targetId: "r-golden",
    authorEn: "Satō Yūko",
    authorJa: "佐藤 裕子",
    authorZh: "佐藤裕子",
    fromEn: "Sendai",
    fromJa: "仙台",
    fromZh: "仙台",
    bodyEn:
      "I sell this shape to first-time visitors from my own city. Hakone in the middle is not decoration — it breaks the rail day. Skip it and Kyoto feels like a terminal.",
    bodyJa:
      "仙台から来る初めての人に、この形を勧めています。途中の箱根は飾りではない。列車の一日を切るためです。省くと京都が終着駅に感じます。",
    bodyZh:
      "仙台来的初次客人，我都推这个结构。中间的箱根不是点缀，是把一整天火车切开。省掉的话，京都会像个终点站。",
    rating: 5,
    stayMonth: "2026-04",
    avatar: "/images/avatars/avatar-yuko.png",
  },
  {
    id: "rv-4",
    targetKind: "ticket",
    targetId: "t-nozomi-tyo-kyo",
    authorEn: "Lin Meiyu",
    authorJa: "林美玉",
    authorZh: "林美玉",
    fromEn: "Kaohsiung",
    fromJa: "高雄",
    fromZh: "高雄",
    bodyEn:
      "I bought Hikari on a Pass, then paid the difference for one Nozomi when a meeting moved. The window at Kyoto is 2 h 12 m if you do not stop at Nagoya for lunch.",
    bodyJa:
      "パスではひかりを買い、会議が動いた便だけのぞみの差額を払いました。名古屋で昼を食べなければ、京都の窓は二時間十二分です。",
    bodyZh:
      "通票上我买光号，只有会议改期的那趟补了希望号的差价。若不在名古屋吃午饭，京都的车窗就是二小时十二分。",
    rating: 4,
    stayMonth: "2026-01",
    avatar: "/images/avatars/avatar-lin.png",
  },
] as const;
